/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REMOTEPROCEDURECALL_H_RPCGEN
#define _REMOTEPROCEDURECALL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define REMOTEPROCEDURECALL 23524541
#define REMOTEPROCEDURECALLVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define MYREMOTEPROCEDURECALL 1
extern  int * myremoteprocedurecall_1(char **, CLIENT *);
extern  int * myremoteprocedurecall_1_svc(char **, struct svc_req *);
extern int remoteprocedurecall_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MYREMOTEPROCEDURECALL 1
extern  int * myremoteprocedurecall_1();
extern  int * myremoteprocedurecall_1_svc();
extern int remoteprocedurecall_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REMOTEPROCEDURECALL_H_RPCGEN */
